---
- hosts: nexus
  become: true
  tasks:

    - name : Download Java 1.8 
      yum:
        name: java-1.8.0-openjdk-devel,git
        state: present

# tasks file for ansible-nexus
    - name: Download nexus_package 
      get_url: url=https://sonatype-download.global.ssl.fastly.net/nexus/3/nexus-3.0.2-02-unix.tar.gz dest=/usr/bin
      tags: download


    - name: Ensure Nexus o/s group exists
      group:
        name: "nexus"
        state: present

    - name: Ensure Nexus o/s user exists
      user:
        name: "nexus"
        group: "nexus"
        shell: "/bin/bash"
        state: present

    # - name: Ensure Nexus installation directory exists
    #   file:
    #       path=/opt/bin/nexus/
    #       state="directory"
    #   sudo: true

    - name: Unpack Nexus download
      unarchive:
          src="/usr/bin/nexus-3.0.2-02-unix.tar.gz"
          dest="/usr/bin"
          creates="/usr/bin/nexus"
          force=no
          copy=false
          owner="nexus"
          group="nexus"
          mode="0755"
      tags: unpack

    # - name: Update symlink nexus-latest
    #   shell: ln -fs `ls -d {{ nexus_installation_dir }}/nexus-*|tail -1` {{ nexus_installation_dir }}/nexus-latest

    # - name: Install createrepo for nexus-yum-repository-plugin
    #   yum: name=createrepo state=installed
    #   when: ansible_os_family == "RedHat"

    # - name: Check if sonatype working directory exists
    #   stat: path="{{ nexus_installation_dir }}/sonatype-work"
    #   register: s_w

    # - name: Move existing sonatype working directory into specified working dir
    #   command: mv "{{ nexus_installation_dir }}/sonatype-work" "{{ nexus_working_dir }}"
    #   when: s_w.stat.exists

    - name: Set permissions and ownership on Nexus installation directory
      file:
          path=/usr/bin/nexus
          state="directory"
          owner="nexus"
          group="nexus"
          mode="0755"
          recurse=true

    # - name: Set permissions and ownership on Nexus work directory
    #   file:
    #       path={{ nexus_working_dir }}
    #       state="directory"
    #       owner="{{ nexus_os_user }}"
    #       group="{{ nexus_os_group }}"
    #       mode="0755"
    #       recurse=true